# Generated by Django 3.1.3 on 2020-12-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_name', models.CharField(max_length=50)),
                ('inference_script', models.FileField(upload_to='algorithms/scripts/')),
                ('saved_model', models.FileField(upload_to='algorithms/saved_models/')),
            ],
        ),
    ]
